name: GCP Terraform Workflow
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write
  
env:
  GH_TOKEN: ${{ secrets.GCP_AUTHENTICATION }}
 
jobs:
  detect-changes: 
     runs-on: ubuntu-latest
     outputs: 
       modified_dirs: ${{ steps.detect.outputs.modified_dirs }}
  
     steps:
       - name: Checkout Repository
	 uses: actions/checkout@v3
  
       - name: Detect changes
	 run: |
	      MODIFIED= $(git diff --name-only HEAD~1 HEAD)
	      MODIFIED_DIRS=()
              if echo "$MODIFIED" | grep -q '^vpc/';then
	        MODIFIED_DIRS+=("vpc)
	      fi
	      if echo "$MODIFIED" | grep -q '^api/';then
	        MODIFIED_DIRS+=("api)
	      fi
	      echo "modified_dirs=$(IFS=,;echo "${MODIFIED_DIRS[*]}")">>$GITHUB_OUTPUT
  terraform-checks:
    needs:detect-changes
    runs-on: ubuntu-latest
      strategy: 
          matrix:
            directory: ${{fromJson(needs.detect-changes.outputs.modified_dirs)}}
          steps: 
            -name: Checkout Repository
             uses: actions/checkout@v3
    
           - name: Set Working Directory
             run: echo "Working Directory is ${{ matrix.directory }}
