name: Create resource using terraform

on: 
  push:
    branches:
  workflow_dispatch:

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps: 
      # Checkout Repository
    - name: Checkout Git Repository
      uses: actions/checkout@v3

    - name: Cache plugin dir
      uses: actions/cache@v2
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: setup TFLint
      uses: terraform-linters/setup-tflint@v2
      with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFlint
      run: tflint -f compact --recursive --force

  tfsec-checks:
    runs-on: ubuntu-latest
    needs: tflint-checks

    steps:
    # Checkout Repository
    - name: Check out git Repository
      uses: actions/checkout@v2

    # Tfsec - Security scanner for Terraform code 
    - name: Run TFsec
      uses: aquasecurity/tfsec-action@v1.0.0
