name: Terraform Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [ opened, synchronize, reopened ]

permissions:
  id-token: write
  contents: read

jobs:
  init:
    runs-on: arc-rs-nonprod

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Terraform Init (Emulation)
        run: |
          cd ${{ github.workspace }}
          terraform init
          terraform validate
  plan:
    runs-on: arc-rs-nonprod
    needs: init

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Terraform Plan
        run: |
          cd ${{ github.workspace }}
          terraform init -reconfigure 
          terraform plan -var-file=*.tfvars -lock=false
